version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: layered.bookstore
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - layered.bookstore

volumes:
  mysql-data:

networks:
  layered.bookstore:
    driver: bridge
